### ISSUE TITLE
One more duplicate data exists when converting json array

### ISSUE THREAD

**Issue by mytherf** [mfatihercik/dsm#22]
JSON:
```
 [

  {
    "id": 8531,
    "category": {
      "id": 0,
      "name": "string"
    },
    "name": "doggie",
    "photoUrls": [
      "string"
    ],
    "tags": [
      {
        "id": 3,
        "name": "string"
      }
    ],
    "status": "available"
  },
  {
    "id": 9009,
    "category": {
      "id": 0,
      "name": "string"
    },
    "name": "doggie",
    "photoUrls": [
      "string"
    ],
    "tags": [
      {
        "id": 2,
        "name": "string"
      }
    ],
    "status": "available"
  }
]

```

yaml:
```
sourceSystem: "ASD"
destinationSystem: "ASDF"
params:
  dateFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
result:
  type: array
  path: ..../
  #  filter: $self.index%3==0
  xml:
    path: "/pets/Pet"
  fields:
    category:
      type: object
      fields:
        id:
          dataType: long
        name:
    #          tagId:
    #             type: object
    #             filter: $self.index==3
    #             path: ../tags
    ##             parentPath: ../tags
    #             xml:
    #               path: /pets/Pet/tags/tag
    #             fields:
    #               id: int
    #               name:
    #
    tagIds:
      dataType: long
      type: array
      path: tags/id
      xml:
        path: tags/tag/id

    id:
      dataType: long
    name:
    status:
    photoUrls:
      type: array
      path: photoUrls
      xml:
        path: photoUrls/photoUrls
    tags:
      type: array
      path: tags
      xml:
        path: tags/tag
      fields:
        id:
          dataType: long
        name:
         
 ```

Unit Test:
```
@Test
    public void parsePet() throws IOException {

        Path rootPath = Paths.get(TestUtils.getTestResourcePath(), pathPlace);

        DSMBuilder builder = new DSMBuilder(rootPath.resolve("pet.yml").toFile(), rootPath.toString());
        DSM dsm = builder.setType(DSMBuilder.TYPE.JSON).create(Pet.class);
        File file = rootPath.resolve("pet.json").toFile();

        Object object = dsm.toObject(file);

        List<Pet> list = (List<Pet>) object;
        String s = JSONUtil.toJsonStr(list);
        System.out.println(s);
    }
```

Result:
```
[
	{
		"photoUrls": [
			"string"
		],
		"tagIds": [
			3
		],
		"tags": [
			{
				"name": "string",
				"id": 3
			}
		],
		"name": "doggie",
		"id": 8531,
		"category": {
			"name": "string",
			"id": 0
		},
		"status": "available"
	},
	{
		"photoUrls": [
			"string"
		],
		"tagIds": [
			2
		],
		"tags": [
			{
				"name": "string",
				"id": 2
			}
		],
		"name": "doggie",
		"id": 9009,
		"category": {
			"name": "string",
			"id": 0
		},
		"status": "available"
	},
	{
		"photoUrls": [
			"string"
		],
		"tagIds": [
			2
		],
		"tags": [
			{
				"name": "string",
				"id": 2
			}
		],
		"name": "doggie",
		"id": 9009,
		"category": {
			"name": "string",
			"id": 0
		},
		"status": "available"
	}
]
```

There are two items with the same id "9009". It seems one more data exists.
I researched there is a new version 1.0.5 to fix similar bug. But when I debuged in the code at "case END_ARRAY", found it go to another condition at line 27 as below.
![image](https://github.com/mfatihercik/dsm/assets/43462802/c0a6232e-75d7-438d-8fb6-143d06600af5)

Is there any missing configuration for me?
@mfatihercik
