### ISSUE TITLE
parsing element is not merged when path is null

### ISSUE THREAD

**Issue by mfatihercik** [mfatihercik/dsm#6]
First:
```yaml

         METHOD:
         -  parentPath: header
            default: $all.result.data.TYPOLOGY
            transformationCode: METHOD
```
Second
```yaml

         METHOD:
         -  parentPath: header
            default: $self.parent.data.TYPOLOGY
```

second extends to first
